### ISSUE TITLE
[Alpha1.0] 캐릭터 시스템 구현

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#1]
## Focus
----
- 에디터를 시작하면 START 버튼이 나오는 스테이지 1번의 탑뷰시점에서 시작한다. Start버튼을 누르면 PC는 지정된 스타트지점으로 시점이 바뀌며 Ready 카운트가 나타난다. Ready 카운트가 0이 되면 유닛이 이동하기 시작한다.
Ready 카운트 중에 플레이어는 자유롭게 이동이 가능하며 스팟1을 향해서 이동한다. 스팟에 도착하면 주변을 관찰하여 미션을 탐색하고 캐릭터액션을 이용해 오브젝트와 상호작용을 하여 문제를 해결한다. 유닛을 최대한 많이 목표지점으로 보내는것이 게임의 목표가 된다.

### 공통
- PC는 데미지를 입지 않는다
- PC컨트롤은 키보드와 마우스를 이용한다.
- PC는 오브젝트의 인터렉션에 따라 행동(애니메이션)한다.
- PC 컨트롤 순서는 테스트후 조정할 수 있다.

### 컨트롤 
- PC컨트롤은 키보드와 마우스를 이용한다.
   - 마우스로 카메라를 이동할 수 있다. (캐릭터 시점한계는 정해야함.) - @baw6114 
   - 상좌하우:WASD
- 플레이어는 화면중앙에 AIM을 통해 타겟오브젝트가 선택되었음을 알수 있다.
- 플레이어의 액션은 근거리액션/ 투사체 액션으로 구분된다.
- 플레이어의 액션은 첫번째 마우스왼쪽클릭으로 ON 두번째 왼쪽클릭으로 효과발동 및 OFF 가된다.
- 각 액션별로 이슈를 생성한다.
- 선택한 타겟오브젝트에 액션이 가능하면 표시된다. (액션별 아이콘필요)
   액션 1. 오브젝트 부양이동 (자석이동 느낌,중력없음) #21 
   액션 2. 오브젝트 attach로 끌어서 위치이동 (버튼 물건올려놓기,중력작용) #22 
   액션 3. 오브젝트 던지기 (중력건스타일) 멀리있는 타겟형태의 버튼작동
   액션 4. 오브젝트 충돌해서 밀기 (마찰력 무시, 컬링효과)
   액션 5. 폭탄 던지기 (중력건 + 시한폭탄)
   액션 6. 오브젝트 자르기 (밧줄끊기, 종유석자르기)
   액션 7. 발사체로 타겟을 맞추면 부유상태가 된다. (물방울 배치필요)

- 타겟한 상태로 마우스 오른쪽 클릭을 하면 해당 액션의 조건이 만족되는지 체크후 액션을 시작한다.

### spec
- [x] 액션컨트롤 플로우 근거리 
    -  액션컨트롤 플로우 (즉시 작동하는 형태)
     1. AIM으로 타겟을 선택
     2. 액션오브젝트는 아이콘 표시
     3. 마우스왼쪽 클릭으로 인터렉션 활성화
     4. 마우스왼쪽 클릭을 다시하면 릴리즈 
- [x] 액션컨트롤 플로우 투사체 (카메라 줌기능 포함)
     - 액션컨트롤 플로우 (투사체로 변경 발동하는 형태)
      1. AIM으로 타겟을 선택
      2. 액션오브젝트는 아이콘 표시 
      3. 마우스 왼쪽 클릭으로 인터렉션 활성화 (시점변경)
      4. 방향결정 
      5. 마운스 왼쪽 클릭을 다시하면 효과발동되면서 해제
- [x] 액션 1. 오브젝트 부양이동 (자석이동 느낌,중력없음) #21 
- [x] 액션 2. 오브젝트 attach로 당기기 위치이동 (버튼 물건올려놓기,중력작용) #22 
- [x] 액션 3. 오브젝트 던지기 (중력건스타일) 멀리있는 타겟형태의 버튼작동 #
- [x] 액션 4. 오브젝트 클릭해서 밀기 (마찰력 무시, 컬링효과) #
- [x] 액션 5. 폭탄 던지기 (중력건 + 시한폭탄) #10 
- [x] 액션 6. 오브젝트 자르기 (밧줄끊기, 물건자르기) #3 
- [x] 액션 8. 물방울맞춰 공중에 띄우기 액션 (중력건 + 풍선효과) #14 
- [x] 액션 9. 오브젝트에 풍선을 생성해 공중에 띄우기 액션 (자르기 + 풍선달기) #13 
- [ ] ~액션 7. 발사체로 타겟을 맞추고 줄에 연결하면 이동이 가능해진다.~

- [x] 캐릭터 오브젝트 AIM시 해당 액션 아이콘 출력

**Comment by gt3973** [comment]
원거리 컨트롤 시스템 구현

**Comment by kyungho-lee** [comment]
## 캐릭터 액션리스트 정리 @gt3973 
1. 들기(Lift) : 일정 높이 이상 들어서 놓을 수 있는 액터.
2. 당기기 (Pull) : 끌어서 당길수 있는 액터
3. 던지기 (Throw) : 캐릭터 앞에 들고 멀리 던질 수 있는 액터 (카메라 앵글변화)
4. 밀기 (Push) : 캐릭터가 충돌해서 밀수 있는 액터.
5. 폭탄던지기 (Bomb throw) : 캐릭터 앞에 들고 던질 수 있는 폭탄 액터 (카메라 앵글변화)
6. 자르기 (Cutting) : 캐릭터앞에 자를 수 있는 액터가 생성되고 맞으면 잘리는 액터 (카메라 앵글변화) 
7. 버블던지기 (Bubble throw) : 캐릭터 앞에 들고 타겟을 향해 쏘는 액터 (카메라 앵글변화)
8. 풍선던지기 (Balloon throw) : 캐릭터앞에 던질 수있는 이펙트가 생성되고 날아가서 맞으면 풍선이 생성되는 액터 (카메라 앵글변화)
